name: Upload Python Package

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Run tests
      run: pytest -v

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Publish to pypi
      env: 
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ env.PYPI_TOKEN }}
      run: twine upload dist/*
