# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Lint with flake8
      run: poetry run flake8 . --max-line-length=127

    - name: Run Pytest
      env:
        USGSXPLORE_USERNAME: ${{ secrets.USGSXPLORE_USERNAME }}
        USGSXPLORE_TOKEN: ${{ secrets.USGSXPLORE_TOKEN }}
      run: poetry run pytest tests/
